name: math
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: '>= 4.7.0'
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
#  test: 1.14.6
#  flutter_driver:
#    sdk: flutter
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/sr1.PNG
    - images/sr2.PNG
    - images/sr3.PNG
    - images/sr4.PNG
    - images/sr5.PNG
    - images/sr6.PNG
    - images/sr7.PNG
    - images/sr8.PNG
    - img_data/img_ds/1.jpg
    - img_data/img_ds/2.jpg
    - img_data/img_ds/3.jpg
    - img_data/img_ds/4.jpg
    - img_data/img_ds/5.jpg
    - img_data/img_ds/6.jpg
    - img_data/img_ds/7.jpg
    - img_data/img_ds/8.jpg
    - img_data/img_ds/9.jpg
    - img_data/img_ds/10.jpg
    - img_data/img_ds/11.jpg
    - img_data/img_ds/12.jpg
    - img_data/img_ds/13.jpg
    - img_data/img_ds/14.jpg
    - img_data/img_ds/15.jpg
    - img_data/img_ds/16.jpg
    - img_data/img_ds/17.jpg
    - img_data/img_ds/18.jpg
    - img_data/img_ds/19.jpg
    - img_data/img_hhgt/1.jpg
    - img_data/img_hhgt/2.jpg
    - img_data/img_hhgt/3.jpg
    - img_data/img_hhgt/4.jpg
    - img_data/img_hhgt/5.jpg
    - img_data/img_hhgt/6.jpg
    - img_data/img_hhgt/7.jpg
    - img_data/img_hhgt/8.jpg
    - img_data/img_hhgt/9.jpg
    - img_data/img_hhgt/10.jpg
    - img_data/img_hhgt/11.jpg
    - img_data/img_hhgt/12.jpg
    - img_data/img_hhgt/13.jpg
    - img_data/img_hhgt/14.jpg
    - img_data/img_hhgt/15.jpg
    - img_data/img_hhgt/16.jpg
    - img_data/img_hhgt/17.jpg
    - img_data/img_hhgt/18.jpg
    - img_data/img_hhgt/19.jpg
    - img_data/img_hhgt/20.jpg
    - img_data/img_hhgt/21.jpg
    - img_data/img_hhgt/22.jpg
    - img_data/img_lg/1.jpg
    - img_data/img_lg/2.jpg
    - img_data/img_lg/3.jpg
    - img_data/img_lg/4.jpg
    - img_data/img_lg/5.jpg
    - img_data/img_lg/6.jpg
    - img_data/img_lg/7.jpg
    - img_data/img_lg/8.jpg
    - img_data/img_lg/9.jpg
    - img_data/img_lg/10.jpg
    - img_data/img_lg/11.jpg
    - img_data/img_lg/12.jpg
    - img_data/img_lg/13.jpg
    - img_data/img_lg/14.jpg
    - img_data/img_lg/15.jpg
    - img_data/img_lg/16.jpg
    - img_data/img_meo/1.jpg
    - img_data/img_meo/2.jpg
    - img_data/img_meo/3.jpg
    - img_data/img_meo/4.jpg
    - img_data/img_meo/5.jpg
    - img_data/img_meo/6.jpg
    - img_data/img_meo/7.jpg
    - img_data/img_meo/8.jpg
    - img_data/img_meo/9.jpg
    - img_data/img_meo/10.jpg
    - img_data/img_meo/11.jpg
    - img_data/img_meo/12.jpg
    - img_data/img_meo/13.jpg
    - img_data/img_meo/14.jpg
    - img_data/img_meo/15.jpg
    - img_data/img_meo/16.jpg
    - img_data/img_meo/17.jpg
    - img_data/img_mt/1.jpg
    - img_data/img_mt/2.jpg
    - img_data/img_mt/3.jpg
    - img_data/img_mt/4.jpg
    - img_data/img_mt/5.jpg
    - img_data/img_mt/6.jpg
    - img_data/img_mt/7.jpg
    - img_data/img_mt/8.jpg
    - img_data/img_tp/1.jpg
    - img_data/img_tp/2.jpg
    - img_data/img_tp/3.jpg
    - img_data/img_tp/4.jpg
    - img_data/img_tp/5.jpg
    - img_data/img_tp/6.jpg
    - img_data/img_tp/7.jpg
    - img_data/img_tp/8.jpg
    - img_data/img_tp/9.jpg
    - img_data/img_tp/10.jpg
    - img_data/img_tp/11.jpg
    - img_data/img_tp/12.jpg
    - img_data/img_tp/13.jpg
    - img_data/img_vp/1.jpg
    - img_data/img_vp/2.jpg
    - img_data/img_vp/3.jpg
    - img_data/img_vp/4.jpg
    - img_data/img_vp/5.jpg
    - img_data/img_vp/6.jpg
    - img_data/img_vp/7.jpg
    - img_data/img_xstk/1.jpg
    - img_data/img_xstk/2.jpg
    - img_data/img_xstk/3.jpg
    - img_data/img_xstk/4.jpg
    - img_data/img_xstk/5.jpg
    - img_data/img_xstk/6.jpg
    - img_data/img_xstk/7.jpg
    - img_data/img_xstk/8.jpg
    - img_data/img_xstk/9.jpg
    - img_data/img_xstk/10.jpg
    - img_data/img_xstk/11.jpg
    - img_data/img_xstk/12.jpg
    - img_data/img_xstk/13.jpg
    - img_data/img_xstk/14.jpg
    - img_data/img_xstk/15.jpg
    - img_data/img_xstk/16.jpg
    - img_data/img_xstk/17.jpg
    - img_data/img_xstk/18.jpg
    - img_data/img_xstk/19.jpg
    - img_data/img_xstk/20.jpg
    - img_data/img_xstk/21.jpg
    - img_data/img_xstk/22.jpg
    - img_data/img_xstk/23.jpg
    - img_data/img_xstk/24.jpg
    - img_data/img_bcb/1.jpg
    - img_data/img_bcb/2.jpg
    - img_data/img_bcb/3.jpg
    - img_data/img_bcb/4.jpg



  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
